// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1) {
  return window['go']['service']['App']['Generate'](arg1);
}

export function GetCauldrons() {
  return window['go']['service']['App']['GetCauldrons']();
}

export function GetPotions() {
  return window['go']['service']['App']['GetPotions']();
}
