// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Generate(arg1:domain.GenerateRequest):Promise<string>;

export function GetCauldrons():Promise<Array<domain.Cauldron>>;

export function GetPotions():Promise<Array<domain.Potion>>;
